### ISSUE TITLE
Incorrect number of packages on Arch

### ISSUE THREAD

**Issue by loki7990** [6gk/fet.sh#19]
Hello,

Thanks for sharing this fetch script! I have noticed one discrepancy however; it looks like the package count for Arch linux is slightly off; I don't know POSIX at all but it looks like the relevant code in fet.sh is counting all files and directories rather than just the directories of the package. On my system, my `/var/lib/pacman/local/` contains a `ALPM_DB_VERSION` file which I don't  think is a part of any singular package.

**Comment by 6gk** [comment]
Eh, whatever, all arch packages are lowercase, it should be as simple as replacing `/*` with `/[a-z0-9]*`
