### ISSUE TITLE
host says 'System Product Name' instead of my motherboard model

### ISSUE THREAD

**Issue by Pistrie** [6gk/fet.sh#24]
I'm not sure what kind of info you would like from me to fix this, but I'll paste a screenshot of the output

![image](https://user-images.githubusercontent.com/39904003/95764515-d7d88200-0cb0-11eb-9817-c775f6c7eb5f.png)

**Comment by 6gk** [comment]
Lets just say I'm not surprised you're on manjaro...

Can you share the contents of /etc/hostname and /proc/sys/kernel/hostname (this is what fet.sh reads)

**Comment by Pistrie** [comment]
I already tried those, and they both show the correct name, 'icarus'.

Also I'm not sure the slight towards me was necessary. I have only used Linux for a couple of months and I'm still learning the ins and outs :(

**Comment by 6gk** [comment]
Nah, it wasn't meant to be against you, but against manjaro. Manjaro has lots of weird issues.

**Comment by 6gk** [comment]
Also I had just woken up, I didn't really look at the screenshot.

The hostname is correct, as shown in the first line (sylvester@icarus)

the 'host' is like the device model, or in my case, my desktop's motherboard model.

**Comment by Pistrie** [comment]
> Nah, it wasn't meant to be against you, but against manjaro. Manjaro has lots of weird issues.
> ~Damn, now I feel bad pensive~

It's fine :smile: 
Is there something I can do on my end to fix this?

**Comment by 6gk** [comment]
I'm not sure to be honest. This is read from `/sys/devices/virtual/dmi/id/product_name`, and I'm not sure if it can be changed on the user's end, at least not easily.

**Comment by Pistrie** [comment]
Forgive my brainfart. For some reason I assumed that in your script 'host' meant hostname. Running cat on `/sys/devices/virtual/dmi/id/product_name` returns 'System Product Name'. I'm going to look around and see if I can fix this somehow

**Comment by 6gk** [comment]
On laptops it's usually the laptop model btw.  
And that's an understandable mistake, don't worry.

**Comment by Pistrie** [comment]
I suppose it doesn't really matter. I'll just alias it out. I tried manually changing it with vim but it seems the file is protected

**Comment by 6gk** [comment]
The file is not an actual file, per se, it's written by the kernel, kind of like /proc.

**Comment by Pistrie** [comment]
One of them did in fact work!

![image](https://user-images.githubusercontent.com/39904003/95789048-12581400-0cdd-11eb-94df-6d628b280a83.png)

**Comment by 6gk** [comment]
Well, that is promising.
So does `/sys/devices/virtual/dmi/id/board_name` have the correct name?

**Comment by Pistrie** [comment]
It does

**Comment by 6gk** [comment]
In that case, I just pushed a few new commits, can you check if it works now?

**Comment by Pistrie** [comment]
Works like a charm!

![image](https://user-images.githubusercontent.com/39904003/95794595-91067e80-0ce8-11eb-80c5-2ae1a5940db8.png)
