### ISSUE TITLE
icewmbg detected instead of IceWM

### ISSUE THREAD

**Issue by zaza42** [6gk/fet.sh#25]
![scrot-2020-10-14-06-34-12_274x238](https://user-images.githubusercontent.com/16356124/95943932-58010380-0de7-11eb-8e10-fad547471826.png)
Its name is [IceWM](https://ice-wm.org/), the icewmbg process only sets the background.
I'm using Debian sid.

**Comment by 6gk** [comment]
i'd recommend just using feh or hsetroot instead of a wm-specific bg setter, unless it has special features that you use like per-workspace wallpapers

**Comment by zaza42** [comment]
![scrot-2020-10-14-06-49-02_304x277](https://user-images.githubusercontent.com/16356124/95944799-5f291100-0de9-11eb-89e1-5d304f775a7f.png)
Ok, thx! I've set with fet.
