### ISSUE TITLE
blocks look wierd

### ISSUE THREAD

**Issue by sheeepdev** [6gk/fet.sh#28]
when i run fet.sh the blocks are wierdly displayed, they are not displayed in my colorscheme and they are very small, and have weird small spaces between them tried resizing the terminal ctrl + or - but it doesn't work

**Comment by 6gk** [comment]
What terminal, what font, what colour scheme, and can you share a screenshot?

My first impressions of this issue is that your terminal doesn't support box-drawing characters (alacritty?), and you're using a colour scheme (such as solarized) which uses colour 0-7 as normal colours, then 8-15 as shades of grey (instead of the light variant).  (This script uses colours 8-15.)

**Comment by sheeepdev** [comment]
Im using hyper, cant send a screenshot because I'm on my main windows machine and Linux is on my laptop, but yeah I'm using hyper and the nord color scheme

**Comment by sheeepdev** [comment]
@6gk actually im sorry the blocks were in the colorscheme of the system and not the terminal, weird shouldn't it pick up the terminal theme or something?, but still, I tried it on uxrtv and it works it doesn't have any spaces..

**Comment by 6gk** [comment]
Without a screenshot I can't really help much, sorry.  When you get back to your laptop, please send an image & I'll try help some more.

I'm also not on linux right now so I can't just install hyper, vomit that i have electron on my system, run fet.sh, then uninstall hyper and clean up the vomit.

**Comment by sheeepdev** [comment]
![2021-01-30-134305_127x41_scrot](https://user-images.githubusercontent.com/68562536/106356598-26159d80-6301-11eb-8145-e76b3fd27528.png)

**Comment by KiranWells** [comment]
I would recommend testing out a few other Unicode characters in the color printing function. It is likely an issue with how your terminal displays the characters. You could also try the block specifying feature I just created a pull request for: #29.
