### ISSUE TITLE
Too aggressive terminal name filter

### ISSUE THREAD

**Issue by g-rden** [6gk/fet.sh#32]
https://github.com/6gk/fet.sh/blob/de8e83b22cb36097ad6ec6243073417549fcd558/fet.sh#L47

`*init*` filters out [`miniterm`](https://github.com/laelath/miniterm) which I use. `*init` would also filter `xinit` out which is the only reason for the filter, I think. If not just ignore this issue.

**Comment by 6gk** [comment]
I believe it was to filter out inits that use a plain ol' `init` binary, and not xinit - close though!

Thanks for the report.
